#!/bin/sh
# The famous "get a menu of emojis to copy" script,
# adapted to Wayland by Eduardo Quiros.
# Original Author: Luke Smith <luke@lukesmith.xyz>
# Original version at: https://raw.githubusercontent.com/LukeSmithxyz/voidrice/master/.local/bin/dmenuunicode
# License: GNU GPLv3, license text at https://www.gnu.org/licenses/gpl-3.0.txt

if [ -z "${WAYLAND_DISPLAY}" ]; then
	clipboard="xclip"
else
	clipboard="wl-copy"
fi

chosen=$(cut -d ';' -f1 "${XDG_DATA_HOME}/emoji" | menu | sed "s/ .*//")

# Exit if none chosen.
[ -z "${chosen}" ] && exit

echo "${chosen}" | tr -d '\n' | ${clipboard}

notify-send "'${chosen}' copied to clipboard." &
