#!/bin/sh
LCYAN='\033[1;36m'
LGREEN='\033[1;32m'
NC='\033[0m' # No Color

print_color () {
	printf "${LCYAN}UPDATING $1${NC}\n"
}

print_sucess () {
	printf "${LGREEN}SUCCESS${NC} ✅\n"
}

[ -e "$(command -v flatpak)" ] && print_color "FLAPAKS" \
	&& flatpak update --assumeyes && print_sucess

[ -e "$(command -v nvim)" ] && print_color "NEOVIM"\
	&& nvim +"au User PackerComplete qa" +PackerSync && print_sucess
# +"silent TSUpdateSync"

print_color "NIXOS" && sudo nixos-rebuild switch --upgrade && print_sucess

