#!/bin/sh
restic backup -r \
	/run/media/"$(whoami)"/2e571771-81db-41a5-a0b6-d5c6d3b8bf88/restic \
	--verbose 3 \
	--password-command="gopass -f restic/snowfort" \
	"${HOME}/.gnupg" \
	"${HOME}/Documents" \
	"${HOME}/Downloads" \
	"${HOME}/Music" \
	"${HOME}/Pictures" \
	"${HOME}/Sync" \
	"${HOME}/Templates" \
	"${HOME}/Videos" \
	"${HOME}/projects" \
	--exclude "*/league-of-legends/*" \
	--exclude "*/oses/*" \
	--exclude "*/node_modules/*" \
	--exclude "${HOME}/Games/battlenet"
