#!/bin/sh
case "$1" in
	o | odysee) url="https://lbryfeed.melroy.org/channel/odysee/$2/json" ;;
	t | twitch) url="https://twitchrss.appspot.com/vod/$2" ;;
	*)
		printf "Unhandled"
		exit 1
		;;
esac

notification="Url: ${url} has been copied to your clipboard!"

2clip "${url}" && printf "${notification}"
notify-send "${notification}"
