#!/bin/sh

[ -e ./.envrc ] || echo "use nix" > .envrc && direnv allow
[ -e shell.nix ] || [ -e default.nix ] \
	|| cp "${HOME}/Templates/nixify/$1.nix" shell.nix \
	|| cat > shell.nix << 'EOF'
with import <nixpkgs> {};
mkShell {
	nativeBuildInputs = [
	];
}
EOF

case "$1" in
	"node") echo "export \$PATH=\$XDG_DATA_DIR/npm/bin:\$PATH" >> ./.envrc;;
	*) echo "Using default envrc";;
esac

${EDITOR} default.nix
