#!/bin/sh
gpg --encrypt --recipient "eduardo@eduardoquiros.com" "$1" \
	&& notify-send -t 5000 "🔒 encrypting..." \
	&& shred "$1" \
	&& notify-send -t 5000 "✎ ovewriting original file..." \
	&& /usr/bin/env rm "$1" \
	&& notify-send -t 5000 "❌ file deleted"
