#!/bin/sh

file="$(realpath "$1")"
directory="${file%/*}"
basename="${file%.*}"
extension="${file##*.}"

latex_cleanup() {
	for ext in aux out log; do
		[ -f "${basename}.${ext}" ] && rm "${basename}.${ext}"
	done
}

case "${extension}" in
	c) cc "${file}" -o "${basename}" ;;
	cpp) c++ "${file}" -o "${basename}" ;;
	docx) libreoffice --convert-to pdf "${file}" ;;
	md) pandoc -t ms --highlight-style kate -s -o "${basename}".pdf "${file}" ;;
#	md) lowdown -X title $< -sTms "${file}" | pdfroff -itk -mspdf  >"${basename}.pdf" ;;
	ms) groff -k -ms "${file}" >> "${basename}.pdf" ;;
	org) pandoc "${file}" -o "${basename}.pdf" ;;
	tex)
		xelatex "$1"
		latex_cleanup "$@"
		;;
	*)
		echo "No idea how to handle that..."
		exit 1
		;;
esac
