#!/bin/sh

encrypted_file="$(realpath "$1")"
decrypted_name="${encrypted_file%.*}"

gpgdecrypt() {
	gpg --output "${decrypted_name}" --decrypt "$1"
}

case "$1" in
	*.gpg) gpgdecrypt "$@" ;;
	*) echo "I can't decrypt that..." ;;
esac

if [ -f "${decrypted_name}" ]; then
	notify-send -t 5000 "✅ file decrypted"
else
	notify-send -t 5000 "❌ decryption failed"
fi
