#!/bin/sh
# Force program to run under xwayland instead of natively on wayland.

export QT_QPA_PLATFORM="xcb"
export GDK_BACKEND="x11"
export XDG_SESSION_TYPE="x11"
export SDL_VIDEODRIVER=x11
exec "$1"
